language: java
jdk:
  - openjdk8
services:
  - docker
matrix:
  fast_finish: true

env:
  global:
    # DOCKER_USER
    - secure: "M1YVktZ7fD+Cde8ciYBUSEIFZTRmZwRXvqWujtx1UcBiWJKYbbeUj6Esi9HdPCZUaK0pG5jxnW1XhLXrN4sJ+JgaZJ+ReCiK+MvOK7JvjPuXnNUYNgXCGtaHnfGOT5zzKSacW+EKOCYPJrszCwPtOq69xm8NEQRfzfZk//DItZTmXR+FswYzeN7DtH1Dk/5zvkYs1I+sAZFZtGZDEqTF2toAe9GRyHAg0KE7RiF6oVcNwcIXNfFANuY8iXq/X3oYQshzGOAEGTovFTNmgX0ElPbp5W36YI7zxrsTyVo4nzbYEIPuxQuOCTOn0M/XPFEHn0lxmQSutdyZZqGgGwbCa+luIpkFZ+jOWm/uz/Ib5gjKvlSiy/IH4G3DORTqu9O0IM37fJs08XJHRFu8bxPWEQuLVgQ4wrTLRCH72MEh63k6b4U4KJ2Y3QdNjnEFL403XTTlQqNZm8xFMX/xaQdUvRItC0haaXjG3ak4c1ilVGWVE4VNk1Mi63f8pxQyzaBfmeaYjQIoOEaUxujylzFQwmpidEijL4ebpomc8pfQMqFZ+my0ZNtGwNifkvGeX/qzyuSMnaS8Oe2MNiNodnrBD0TGvG/mSd+/shFTAB7Qu42w05apsdyd+Xn9C6CnU8wVoGDbWwb5Yjm5q1Ag/Z9f0Lu5EjDYEqc12lXKaqt3wb4="
    # DOCKER_PASSWORD
    - secure: "yiMrYbl4OIn47LWoOvbQeSRAgLycG2NHdFR7XUvCdRSD9JbOs7LtOfp8lbNBj0khDqr1jcsE0Ne4duJ/SgI70mwnRrNJjWHrJu1RtrSKH1SZbumKqKI+YAkc4xFJy3n+0l8cCZIZcWLVdde+nJ42dvE6VfmYnxl7oohXJ+NMxGNe8hARTs7FdGRq6H7/Pu1bP4dhhz2DUeXqhNfRs4KWd/f2na+niu8FIniadDX3O0HYQbCMXqz0DfqqqsLu+oLiATiQt+pdaS0a/7tmzL5viy4TNbok485BU4S3mGYv8jYXai1LatbO1QIbhSvedlUks8nTtiw6WrWsm9EeGvFu4wsFdLwNCe8szd/b84q0yPdU8vYy93d1TKi0PjOJ8/W/qQzcmwns2HypdXWJLhDEG1Xey5xWy+7RP/p0FWZNBxq1HRb0DMDGtqVT3cVuLrpr7YmqwK5oRd0ubzHkxEvsSQ3ugfyb1bieYS7CNiMrZl6BpL0/TzCHdQcC4h30BOvH8I/V+nt8+d3+ViIDMPWg4nNMESwQNT5tu0CKlv8UD0OMSeRx4wPKz0TOXrynuYg2f/JoNvJ/Y100MxzuNOLNr890flX2491zx/1GK7odxJSQtw99FwTTsERC+Jw+SVWncfRRJhj32ioaLax6IoMQKqdgDN5HPut+43qKDwYp20M="
    - IMAGE_NAME=baloiseincubator/argonaut

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=$(if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$BRANCH-$COMMIT"; fi | sed 's/\//-/')
  - docker build . -t $IMAGE_NAME:latest
  - if [ $BRANCH = "master" ]; then docker tag $IMAGE_NAME:latest $IMAGE_NAME:master; fi
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest
  - if [ $BRANCH = "master" ]; then docker push $IMAGE_NAME:master; fi
  - docker push $IMAGE_NAME:$TAG

cache:
  directories:
    - '$HOME/.m2/repository'